### ISSUE TITLE
clone 下来报错

### ISSUE THREAD

**Issue by ayw** [chendongMarch/SocialSdkLibrary#1]
Error:(1, 0) Plugin with id 'com.android.library' not found.
<a href="openFile:C:\Users\kevin\AndroidStudioProjects\SocialSdkLibrary\build.gradle">Open File</a>

**Comment by chendongMarch** [comment]
@ayw 

我重新整理了gradle文件，我用的是AS3.0 gradle 3.3.1,这个我们不一样的话可能会有问题，你可以把build.gradle针对自己的项目调整一下。

最近代码做了一些重构，本地运行是没问题的，建议看一下最新的代码是否还有问题，谢谢。

**Comment by ayw** [comment]
更新合并了你的工程还是编译不过，能否加个联系方式在线看看呢，我是全新clone下来也不行，全用你工程里面的配置QQ：1026759937

在 2017年12月8日 下午7:41，chendong <notifications@github.com>写道：

**Comment by pys200603027** [comment]
您好作者，感想提供这个库
我也是clone下来编译报错，错误整理如下

*错误1*
```
ERROR: Plugin with id 'testbuildsrc' not found.
```

尝试删除`app/build.gradle`中的`apply plugin: 'testbuildsrc`,继续编译

*错误2*
```
ERROR: Could not get unknown property 'storePassword' for project ':app' of type org.gradle.api.Project.
```

尝试删除`app/build.gradle`中如下代码
```
//正式签名相关信息
    signingConfigs {
        babyphoto {
            storeFile file("sja.jks")
            storePassword project.storePassword
            keyAlias project.keyAlias
            keyPassword project.keyPassword
            v2SigningEnabled false
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.babyphoto
        }
        debug {
            signingConfig signingConfigs.babyphoto
        }
    }

buildTypes {
        release {
            signingConfig signingConfigs.babyphoto
        }
        debug {
            signingConfig signingConfigs.babyphoto
        }
    }

```
继续编译。。。

*错误3*

```
ERROR: Cause: null value in entry: qq_id=null
```

无法继续了，请求作者帮助

**Comment by chendongMarch** [comment]
@pys200603027  你好，麻烦 `clone` 一下  `master` 最新的代码。

1. 每个平台的 `appId/appKey` 不会上传到 `git` 上面，需要在 `local.properties` 里面如下配置:

```
wxAppId = wx4******195c3
wxAppSecret = 0a3cb00729******e3654f499171
wxOnlyAuthCode = false

qqAppId = 110******200
qqAppSecret = A6Aqt******59yQ4N

wbAppId = 21896******98
wbUrl = http://open.manfenmm.c******mon.php

ddAppId = dingoag******umuof
```
2. 关于 `testBuildSrc` 是我本地调试遗留的测试代码，是我的锅，新的版本我已经移除了。
3. 你如果不是使用 `gradle` 依赖，那么你  `SocialPlugin` 这个插件的依赖可能要调整一下，项目中依赖的本地的。

如果还有问题你可以加我 QQ  1101873740

**Comment by pys200603027** [comment]
> @pys200603027 你好，麻烦 `clone` 一下 `master` 最新的代码。
> 
> 1. 每个平台的 `appId/appKey` 不会上传到 `git` 上面，需要在 `local.properties` 里面如下配置:
> 
> ```
> wxAppId = wx4******195c3
> wxAppSecret = 0a3cb00729******e3654f499171
> wxOnlyAuthCode = false
> 
> qqAppId = 110******200
> qqAppSecret = A6Aqt******59yQ4N
> 
> wbAppId = 21896******98
> wbUrl = http://open.manfenmm.c******mon.php
> 
> ddAppId = dingoag******umuof
> ```
> 1. 关于 `testBuildSrc` 是我本地调试遗留的测试代码，是我的锅，新的版本我已经移除了。
> 2. 你如果不是使用 `gradle` 依赖，那么你  `SocialPlugin` 这个插件的依赖可能要调整一下，项目中依赖的本地的。
> 
> 如果还有问题你可以加我 QQ 1101873740

好的，感谢作者的热心
