### ISSUE TITLE
关于第三方sdk的接入，是否可以换个方案

### ISSUE THREAD

**Issue by kaleai** [chendongMarch/SocialSdkLibrary#10]
通过代码了解到，目前接入的方案都是这个框架支持这个sdk才能接入，比如我想要接入一个公司内部的sdk则不太方便。

可否产生一个plugin的形式呢？通过addPlugin()的方式来添加，在不同的plugin中定义返回的id，和action。

当然，因为各个sdk的差异性是很大的，实现这点并不容易，所以仅仅是一个建议。

**Comment by chendongMarch** [comment]
我目前的打算是等功能相对稳定之后，做一个 base 库，每个平台做一个  func 库，需要哪个就引入哪个，做到可插拔，目前还在做。

**Comment by kaleai** [comment]
好的
