### ISSUE TITLE
android studio 3.3.2 demo 各种运行不起来

### ISSUE THREAD

**Issue by taosimple** [chendongMarch/SocialSdkLibrary#13]
android studio 3.3.2 demo 各种运行不起来，解决一个又来一个，放弃了

**Comment by chendongMarch** [comment]
开发的时候原本的希望为大家提供 gradle plugin 的接入方式，对 Demo clone 下来的运行这部分没有特别关注，不过在我本地是完全可以运行的，你看有没有可能是

local.properties 里面定义了所有的 key, 这个不能公开，你需要把你自己的 key 写在里面，可以参考：

```
wxAppId = wx4b8xxxb195c3
wxAppSecret = 0a3cxxxxxx654f499171
wxOnlyAuthCode = false
```
另外因为 密钥文件、包名、AppId、AppKey 都有比较强的绑定关系，这个因项目的不同也会不同，是不能通用的，得换成你自己的，所以通常不能直接运行 Demo, 可以把模块引入到项目中；

我本地的环境：
gradle ： 3.1.4
gradle-wrapper: 4.4
AS: 3.3.2

如果有问题，请加我 QQ 1101873740  😊我们一起来调一下，然后我出一个  Demo 运行手册

**Comment by taosimple** [comment]
感谢哈，我 gradle 和 Android studio 版本一样，暂时换了一种方法
