### ISSUE TITLE
取消分享 也走回调分享成功

### ISSUE THREAD

**Issue by addappcn** [chendongMarch/SocialSdkLibrary#17]

**Comment by chendongMarch** [comment]
你好，两种场景：

1. 用户点击取消分享，因为微信的限制，取消时仍旧会返回成功，这个是微信防止强制用户分享作出的限制；[参考微信开发文档](https://open.weixin.qq.com/cgi-bin/announce?spm=a311a.9588098.0.0&action=getannouncement&key=11534138374cE6li&version=)

2. 如果分享完成后，用户选择停留在微信而不是返回 App,  这种场景可在 SDK 初始化时加入参数

```java
builder.shareSuccessIfStay(true)
```
用户选择停留在微信时会返回成功


如果还有问题，可以联系我 Q: 1101873740

**Comment by addappcn** [comment]
那就是微信的问题，谢谢
