### ISSUE TITLE
关于集成后 线上bugly统计错误

### ISSUE THREAD

**Issue by wangshaolei** [chendongMarch/SocialSdkLibrary#19]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.dofun.zhw.lite/com.zfy.social.wx.uikit.WxActionActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.zfy.social.core.listener.OnLoginStateListener.onState(android.app.Activity, com.zfy.social.core.model.LoginResult)' on a null object reference

**Comment by chendongMarch** [comment]
感谢支持，最近正在优化插件代码，近期会发布新版本修复这个问题；

**Comment by chendongMarch** [comment]
[1.2.0 版本发布](https://github.com/chendongMarch/SocialSdkLibrary/releases/tag/1.2.0)
