### ISSUE TITLE
invoke SocialSdk.init() first please

### ISSUE THREAD

**Issue by blazert** [chendongMarch/SocialSdkLibrary#2]
我已经在Application里面初始化了啊  但是还是报这个错
W/System.err: java.lang.IllegalStateException: invoke SocialSdk.init() first please
W/System.err:     at com.march.socialsdk.SocialSdk.getConfig(SocialSdk.java:36)
W/System.err:     at com.march.socialsdk.utils.LogUtils.e(LogUtils.java:43)
W/System.err:     at com.march.socialsdk.adapter.impl.RequestAdapterImpl.getFile(RequestAdapterImpl.java:45)
W/System.err:     at com.march.socialsdk.manager.ShareManager.prepareImageInBackground(ShareManager.java:101)
W/System.err:     at com.march.socialsdk.manager.ShareManager.access$100(ShareManager.java:38)
W/System.err:     at com.march.socialsdk.manager.ShareManager$3.call(ShareManager.java:57)
W/System.err:     at com.march.socialsdk.manager.ShareManager$3.call(ShareManager.java:54)
W/System.err:     at bolts.Task$4.run(Task.java:357)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
I/System.out: errCode = 0, errMsg = onPrepareInBackground error
I/System.out: 其他错误 : invoke SocialSdk.init() first please

**Comment by chendongMarch** [comment]
你的 application 在 manifest 里面注册了吗？
