### ISSUE TITLE
微博未安装客户端的情况，不能直接用网页登录和分享

### ISSUE THREAD

**Issue by smuwjs** [chendongMarch/SocialSdkLibrary#4]
1. 微博未安装客户端的情况，不能直接用网页登录和分享

**Comment by smuwjs** [comment]
2. OnLoginListener和OnShareListener的onStart回调未调用。

**Comment by chendongMarch** [comment]
好的，开发的时候微博这边关注的不多，可能问题比较多，后面准备重新写一下

**Comment by smuwjs** [comment]
@chendongMarch 你代码设计的很好，加油，持续关注。

**Comment by chendongMarch** [comment]
onStart 的问题已经 fix,,微博的问题怕是要后面再重写了

**Comment by chendongMarch** [comment]
微博已经升级到 4.1 最新版本，升级 v2 版本 openApi , 并支持网页授权

**Comment by smuwjs** [comment]
给力。

**Comment by smuwjs** [comment]
@chendongMarch 
![image](https://user-images.githubusercontent.com/12137473/41836681-11c7ca34-788e-11e8-92a3-f8d15f0192fb.png)
这样初始化的话，回调的时候变成调用的Activity，并不是回调到ActionActivity。

**Comment by chendongMarch** [comment]
我看了下这个问题倒不在于回调，回调是可以获取到的，真正回调触发在 handleIntent 里面

![image](https://user-images.githubusercontent.com/11373923/41891967-16365304-7949-11e8-9a33-c1cdbfe53fab.png)

WbShareHandler 里面的 context, 主要用于发送注册广播，打开微博 app 等操作，不过这个确实是个问题，我把 WbShareHandler 改成了延迟创建的啦，然后构造方法入参还是收敛成 Context, 这样更合适一些。

另外发现分享，使用 web 的话回调有问题，暂时强制分享必须安装app, 登录可以 web 授权。

![image](https://user-images.githubusercontent.com/11373923/41891942-fde25500-7948-11e8-9d4d-b7b59209436f.png)

**Comment by smuwjs** [comment]
好的，谢谢提醒，我去看了源码，确实是这样子的。
