### ISSUE TITLE
请不要使用我开源项目的头图，否则请按照license进行标明

### ISSUE THREAD

**Issue by kaleai** [chendongMarch/SocialSdkLibrary#7]
SocialSdkLibrary用的介绍图片和我项目的图片是一致的，这是我个人做的图片，请不要随意使用。如果需要使用请写明license。

https://github.com/tianzhijiexian/ShareLoginLib
![image](https://user-images.githubusercontent.com/9552155/44661208-88855800-aa3c-11e8-8206-445cfc632d52.png)

**Comment by laobie** [comment]
使用 Google 以图搜图并没发现这张图是公开可直接使用的，所以请尊重别人的劳动成果，遵守这个社区的规则。

**Comment by yangxueya1983** [comment]
+1

**Comment by shixinzhang** [comment]
作者你好，开源项目借用别人的任何成果都要加上引用说明，无论代码还是图片，请尊重别人的劳动成果。

**Comment by sfyc23** [comment]
请遵循开源协议，尊重别人的劳动成果。

**Comment by czn6** [comment]
请尊重别人的劳动成果 要点脸

**Comment by lixiaodaoaaa** [comment]
请尊重别人的劳动成果 要点13脸

**Comment by lixiaodaoaaa** [comment]
作者你好。请你不要使用 @tianzhijiexian  的图片 谢谢。

① 请尊重原创作者版权
② 若使用 请注明版权 或者加licence
③ 谢谢

**Comment by notHide** [comment]
请不要窃取别人的劳动成果

**Comment by chendongMarch** [comment]
@tianzhijiexian 您好，很抱歉因为我的不专业给您造成影响，我确实没有想到会引起这么严重的后果，我会删除相关的图片，并在这里声明。但是请相信我是没有恶意的，类库的设计、开发也包含了我的心血，我绝对不是抄袭剽窃他人成果的人，抱歉。

最后，再次道歉。

**Comment by chendongMarch** [comment]
@tianzhijiexian 看到您在我博客下面的评论，可能觉得我剽窃了您的代码，特别来解释一下，下面是我在博客下面的评论。

图片的事情很抱歉，是我一时疏忽，没有考虑到侵权的问题，我会删除相关的图片。

之前您就给我提过 issue ，[](https://github.com/chendongMarch/SocialSdkLibrary/issues/3), 我们也有过相关的技术交流，那个时候您没提到图片版权的事情，其实那个时候您但凡跟我说一声，我都会把图片删掉的，因为我当时确实没意识到这个问题。

至于您说的 api 雷同，那我就太冤枉了，我一共只有两个暴露 api, share 和 login, 这两个都不是什么特殊词汇，而且入参也完全不同，另外如果您看过我的代码设计就知道我并没有抄袭您的项目，每一行代码都是我仔细斟酌一行一行打出来，并且经过了很多次的迭代，才有今天的样子。

最后，图片的事情我真的很抱歉，是我考虑不周，这次是个教训，以后我不会再随便找图用了，谢谢您的指正。

**Comment by kaleai** [comment]
主要是看到掘金上“尚妆产品技术刊读”有个这个头图所以专门看了一下，于是就在下方评论了。很感谢你的理解，因为那个图是我自己做的，所以比较在意。

代码方面其实并没有什么问题，那句仅仅是我的一个抱怨，所以希望以后还可以持续的交流。
